###
# dotfiles.yaml
#
# Description:
# - This file contains list of dotfile/config folders to update.
###
applications:
  kitty: "${HOME}/.config/kitty/"
  zellij: "${HOME}/.config/zellij/"
  ytfzf: "${HOME}/.config/ytfzf/"
  hypr: "${HOME}/.config/hypr/"
  yazi: "${HOME}/.config/yazi/"
  fastfetch: "${HOME}/.config/fastfetch/"
  waybar: "${HOME}/.config/waybar/"
  wofi: "${HOME}/.config/wofi/"
  btop: "${HOME}/.config/btop/"
  alacritty: "${HOME}/.config/alacritty/"
  posting: "${HOME}/.config/posting/"
  starship: "${HOME}/.config/starship/"
  neovide: "${HOME}/.config/neovide/"
  swaync: "${HOME}/.config/swaync/"
  lazygit: "${HOME}/.config/lazygit/"
  lazydocker: "${HOME}/.config/lazydocker/"
  lazysql: "${HOME}/.config/lazysql/"
  k9s: "${HOME}/.config/k9s/"
  lsd: "${HOME}/.config/lsd/"
  bat: "${HOME}/.config/bat/"
  wlogout: "${HOME}/.config/wlogout/"

