colors:
  background: "#1E1E2E"      # Base
  foreground: "#CDD6F4"      # Text
  cursor: "#89B4FA"          # Blue
  selection: "#313244"       # Surface0
  directory: "#89DCEB"       # Sky
  file: "#A6E3A1"            # Green
  symlink: "#FAB387"         # Peach
  executable: "#F38BA8"      # Red
  header: "#CBA6F7"          # Mauve
  border: "#585B70"          # Surface2
  hint: "#F9E2AF"            # Yellow
  info: "#94E2D5"            # Teal
  error: "#EBA0AC"           # Maroon
  
  status_bar:
    background: "#181825"  # Mantle
    foreground: "#CDD6F4"  # Text
    highlighted: "#CBA6F7" # Mauve (or any accent color you prefer)

